openapi: 3.0.0
info:
  title: TL21-88
  version: 1.0.0
servers:
  - url: http://localhost:9103
tags:
  - name: auth
  - name: admin
paths:
  /interoperability/api/login:
    post:
      tags:
        - auth
      summary: Login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                username:
                  type: string
                  example: christos
                password:
                  type: integer
                  example: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/logout:
    post:
      tags:
        - auth
      summary: Logout
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/admin/usermod/christos/123456:
    post:
      tags:
        - admin
      summary: Usermod
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/admin/users/christos:
    get:
      tags:
        - admin
      summary: users
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/admin/system/passesudp:
    post:
      tags:
        - admin
      summary: System passes udp
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/admin/healthcheck:
    get:
      tags:
        - admin
      summary: Healthcheck
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/admin/resetpasses:
    post:
      tags:
        - admin
      summary: Reset passes
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/admin/resetstations:
    post:
      tags:
        - admin
      summary: Reset stations
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/admin/resetvehicles:
    get:
      tags:
        - admin
      summary: Reset vehicles
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/PassesPerStation/stationID/2021-12-12T20:49:35Z/2021-12-18T20:49:35Z:
    get:
      tags:
        - default
      summary: Passes per station
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/PassesAnalysis/op1_ID/op2_ID/2021-12-12T20:49:35Z/2021-12-18T20:49:35Z:
    get:
      tags:
        - default
      summary: Passes Analysis
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/PassesCost/op1_ID/op2_ID/2021-12-12T20:49:35Z/2021-12-18T20:49:35Z:
    get:
      tags:
        - default
      summary: Passes Cost
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /interoperability/api/ChargesBy/op_ID/2021-12-12T20:49:35Z/2021-12-18T20:49:35Z:
    get:
      tags:
        - default
      summary: Charges By
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
